-- Создание таблицы для заметок избранного
CREATE TABLE IF NOT EXISTS FAVORITE_NOTES (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    CONTENT TEXT,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME,
    USER_ID BIGINT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

-- Создание индексов для оптимизации
CREATE INDEX IF NOT EXISTS idx_favorite_notes_user_id ON FAVORITE_NOTES(USER_ID);
CREATE INDEX IF NOT EXISTS idx_favorite_notes_updated_at ON FAVORITE_NOTES(UPDATED_AT DESC);